/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OperatorRouteImport } from './routes/_operator'
import { Route as AuRevoirRouteImport } from './routes/au-revoir'
import { Route as HealthRouteImport } from './routes/health'
import { Route as RefusRouteImport } from './routes/refus'
import { Route as OperatorIndexRouteImport } from './routes/_operator/index'
import { Route as OperatorOffresRouteImport } from './routes/_operator/offres'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthConnexionRouteImport } from './routes/auth/connexion'
import { Route as AuthSortieRouteImport } from './routes/auth/sortie'
import { Route as OperatorAppsIndexRouteImport } from './routes/_operator/apps.index'
import { Route as OperatorAppsAppIdRouteImport } from './routes/_operator/apps.$appId'

const OperatorRoute = OperatorRouteImport.update({
  id: '/_operator',
  getParentRoute: () => rootRouteImport,
} as any)
const AuRevoirRoute = AuRevoirRouteImport.update({
  id: '/au-revoir',
  path: '/au-revoir',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const RefusRoute = RefusRouteImport.update({
  id: '/refus',
  path: '/refus',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorIndexRoute = OperatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorOffresRoute = OperatorOffresRouteImport.update({
  id: '/offres',
  path: '/offres',
  getParentRoute: () => OperatorRoute,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConnexionRoute = AuthConnexionRouteImport.update({
  id: '/auth/connexion',
  path: '/auth/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSortieRoute = AuthSortieRouteImport.update({
  id: '/auth/sortie',
  path: '/auth/sortie',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorAppsIndexRoute = OperatorAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorAppsAppIdRoute = OperatorAppsAppIdRouteImport.update({
  id: '/apps/$appId',
  path: '/apps/$appId',
  getParentRoute: () => OperatorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof OperatorIndexRoute
  '/au-revoir': typeof AuRevoirRoute
  '/health': typeof HealthRoute
  '/refus': typeof RefusRoute
  '/offres': typeof OperatorOffresRoute
  '/api/events': typeof ApiEventsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/connexion': typeof AuthConnexionRoute
  '/auth/sortie': typeof AuthSortieRoute
  '/apps/$appId': typeof OperatorAppsAppIdRoute
  '/apps/': typeof OperatorAppsIndexRoute
}
export interface FileRoutesByTo {
  '/au-revoir': typeof AuRevoirRoute
  '/health': typeof HealthRoute
  '/refus': typeof RefusRoute
  '/offres': typeof OperatorOffresRoute
  '/api/events': typeof ApiEventsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/connexion': typeof AuthConnexionRoute
  '/auth/sortie': typeof AuthSortieRoute
  '/': typeof OperatorIndexRoute
  '/apps/$appId': typeof OperatorAppsAppIdRoute
  '/apps': typeof OperatorAppsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_operator': typeof OperatorRouteWithChildren
  '/au-revoir': typeof AuRevoirRoute
  '/health': typeof HealthRoute
  '/refus': typeof RefusRoute
  '/_operator/offres': typeof OperatorOffresRoute
  '/api/events': typeof ApiEventsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/connexion': typeof AuthConnexionRoute
  '/auth/sortie': typeof AuthSortieRoute
  '/_operator/': typeof OperatorIndexRoute
  '/_operator/apps/$appId': typeof OperatorAppsAppIdRoute
  '/_operator/apps/': typeof OperatorAppsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/au-revoir'
    | '/health'
    | '/refus'
    | '/offres'
    | '/api/events'
    | '/auth/callback'
    | '/auth/connexion'
    | '/auth/sortie'
    | '/apps/$appId'
    | '/apps/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/au-revoir'
    | '/health'
    | '/refus'
    | '/offres'
    | '/api/events'
    | '/auth/callback'
    | '/auth/connexion'
    | '/auth/sortie'
    | '/'
    | '/apps/$appId'
    | '/apps'
  id:
    | '__root__'
    | '/_operator'
    | '/au-revoir'
    | '/health'
    | '/refus'
    | '/_operator/offres'
    | '/api/events'
    | '/auth/callback'
    | '/auth/connexion'
    | '/auth/sortie'
    | '/_operator/'
    | '/_operator/apps/$appId'
    | '/_operator/apps/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  OperatorRoute: typeof OperatorRouteWithChildren
  AuRevoirRoute: typeof AuRevoirRoute
  HealthRoute: typeof HealthRoute
  RefusRoute: typeof RefusRoute
  ApiEventsRoute: typeof ApiEventsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthConnexionRoute: typeof AuthConnexionRoute
  AuthSortieRoute: typeof AuthSortieRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_operator': {
      id: '/_operator'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/au-revoir': {
      id: '/au-revoir'
      path: '/au-revoir'
      fullPath: '/au-revoir'
      preLoaderRoute: typeof AuRevoirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refus': {
      id: '/refus'
      path: '/refus'
      fullPath: '/refus'
      preLoaderRoute: typeof RefusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_operator/': {
      id: '/_operator/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof OperatorIndexRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/offres': {
      id: '/_operator/offres'
      path: '/offres'
      fullPath: '/offres'
      preLoaderRoute: typeof OperatorOffresRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/connexion': {
      id: '/auth/connexion'
      path: '/auth/connexion'
      fullPath: '/auth/connexion'
      preLoaderRoute: typeof AuthConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sortie': {
      id: '/auth/sortie'
      path: '/auth/sortie'
      fullPath: '/auth/sortie'
      preLoaderRoute: typeof AuthSortieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_operator/apps/': {
      id: '/_operator/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof OperatorAppsIndexRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/apps/$appId': {
      id: '/_operator/apps/$appId'
      path: '/apps/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof OperatorAppsAppIdRouteImport
      parentRoute: typeof OperatorRoute
    }
  }
}

interface OperatorRouteChildren {
  OperatorOffresRoute: typeof OperatorOffresRoute
  OperatorIndexRoute: typeof OperatorIndexRoute
  OperatorAppsAppIdRoute: typeof OperatorAppsAppIdRoute
  OperatorAppsIndexRoute: typeof OperatorAppsIndexRoute
}

const OperatorRouteChildren: OperatorRouteChildren = {
  OperatorOffresRoute: OperatorOffresRoute,
  OperatorIndexRoute: OperatorIndexRoute,
  OperatorAppsAppIdRoute: OperatorAppsAppIdRoute,
  OperatorAppsIndexRoute: OperatorAppsIndexRoute,
}

const OperatorRouteWithChildren = OperatorRoute._addFileChildren(
  OperatorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  OperatorRoute: OperatorRouteWithChildren,
  AuRevoirRoute: AuRevoirRoute,
  HealthRoute: HealthRoute,
  RefusRoute: RefusRoute,
  ApiEventsRoute: ApiEventsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthConnexionRoute: AuthConnexionRoute,
  AuthSortieRoute: AuthSortieRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
